bycrud:
  ## 模板路径
  source:
    entity: generate/entity.java.vm
    controller: generate/controller.java.vm
    mapper: generate/mapper.java.vm
    mapping: generate/mapping.xml.vm
    service: generate/service.java.vm
    serviceImpl: generate/serviceImpl.java.vm
    saveAO: generate/saveAO.java.vm
    pageAO: generate/pageAO.java.vm
    api: generate/api.js.vm
    html: generate/view.html.vm
    vue: generate/vue.vue.vm
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true