server:
  port: 8888
spring:
  application:
    name: wei-code-generate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.4.30:3306/life?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

bycrud:
  ## 模板对应的生成包路径
  packages:
    entity: model
    mapping: mapper
    controller: controller
    service: service
    serviceImpl: service.impl
    saveAO: pojo
    pageAO: pojo
  ## 数据库类型转换为java 类型对应
  type:
    char: String
    varchar: String
    text: String
    int: Integer
    tinyint: Integer
    date: Date
    datetime: Date
    timestamp: Date
    bigint: Long
  ##自定义前缀
  prefix:
    controller: Api
  ##自定义后缀
  suffix:
    entity: Model
    controller: Controller
    mapper: Mapper
    mapping: Mapping
    service: Service
    serviceImpl: Impl
    saveAO: SaveAO
    pageAO: PageAO
    api: Service